/* ------------------------------------------------------------------
   Builds lang/<code>.js for every language except Arabic, which is
   hand-written in full at lang/ar.js.

   The source is positional: each English key is written once, followed
   by one translation per language in LANGS order. That keeps the source
   readable side by side — you can see all twelve renderings of a line
   at once — and every row is length-checked, so a miscount is caught
   here rather than showing up as Turkish copy on the Japanese page.

   Run:  npm run lang
   ------------------------------------------------------------------ */
'use strict';
const fs = require('fs');
const path = require('path');

const LANGS = ['zh','ja','ru','uz','tr','es','fr','de','it','pt','ur'];

const TITLES = {
  zh: 'ARQR | 把你的展厅搬进他们的房间',
  ja: 'ARQR | あなたのショールームを、お客様の部屋に',
  ru: 'ARQR | ваш шоурум в их комнате',
  uz: 'ARQR | savdo zalingiz ularning xonasida',
  tr: 'ARQR | mağazanız, onların odasında',
  es: 'ARQR | tu showroom, en su habitación',
  fr: 'ARQR | votre showroom, chez eux',
  de: 'ARQR | Ihr Showroom, in deren Raum',
  it: 'ARQR | il tuo showroom, in casa loro',
  pt: 'ARQR | o seu showroom, na sala deles',
  ur: 'ARQR | آپ کا شو روم، اُن کے کمرے میں'
};

const parts = ['part1','part2','part3'].map(f =>
  require(path.join(__dirname, 'lang-source', f + '.js')));

/* ---- merge and check ---- */
const text = {}, attrs = {};
let rows = 0, bad = [];

function take(src, into, label){
  Object.keys(src).forEach(k => {
    const v = src[k];
    if (!Array.isArray(v) || v.length !== LANGS.length)
      bad.push(label + '  "' + k.slice(0, 48) + '"  has ' +
               (Array.isArray(v) ? v.length : 'no') + ' entries, expected ' + LANGS.length);
    if (into[k]) bad.push('duplicate key: "' + k.slice(0, 48) + '"');
    into[k] = v; rows++;
  });
}

parts.forEach((p, i) => {
  take(p.t || {}, text,  'part' + (i + 1) + ' t');
  take(p.a || {}, attrs, 'part' + (i + 1) + ' a');
});

if (bad.length){
  console.error('\n  ' + bad.length + ' problem(s):');
  bad.slice(0, 20).forEach(b => console.error('    ' + b));
  process.exit(1);
}

/* ---- emit ---- */
if (!fs.existsSync('lang')) fs.mkdirSync('lang');

const q = s => JSON.stringify(s);

LANGS.forEach((code, i) => {
  const lines = [];
  lines.push('/* ' + code + ' | generated by build-lang.js, do not edit by hand.');
  lines.push('   Edit lang-source/part*.js and run: npm run lang */');
  lines.push('window.ARQR_LANG = {');
  lines.push('  code: ' + q(code) + ',');
  lines.push('  title: ' + q(TITLES[code]) + ',');
  lines.push('  t: {');
  const tk = Object.keys(text);
  tk.forEach((k, n) => {
    lines.push('    ' + q(k) + ': ' + q(text[k][i]) + (n === tk.length - 1 ? '' : ','));
  });
  lines.push('  },');
  lines.push('  a: {');
  const ak = Object.keys(attrs);
  ak.forEach((k, n) => {
    lines.push('    ' + q(k) + ': ' + q(attrs[k][i]) + (n === ak.length - 1 ? '' : ','));
  });
  lines.push('  }');
  lines.push('};');
  fs.writeFileSync(path.join('lang', code + '.js'), lines.join('\n') + '\n', 'utf8');
});

console.log('  ' + rows + ' strings x ' + LANGS.length + ' languages');
console.log('  wrote ' + LANGS.map(c => c + '.js').join(', '));
console.log('  (ar.js is hand-written and left alone)');
