/* ------------------------------------------------------------------
   Writes the logo into the pages.

   Two pictures, because the header needs two shapes. The lockup is the
   client's monogram and wordmark side by side at 5.52:1, which is what a
   78px bar can show with the wordmark still readable. The monogram on
   its own is 1.87:1 and is what the bar falls back to on a scrolled
   phone, where the samples button has arrived and there is no room for a
   name beside it.

   Both carry their pixel dimensions as attributes, and the CSS then only
   ever sets a height. The attributes give the browser the proportion
   before the file arrives, so the bar does not jump when it does, and
   the width never has to be restated at seven breakpoints.

   The block between the markers is generated. Run this after
   logo-images.js:  npm run logo
   ------------------------------------------------------------------ */
'use strict';
const fs = require('fs');
const sharp = require('sharp');

const START = '<!-- logo:start, generated by logo-write.js -->';
const END = '<!-- logo:end -->';

/* Named rather than left to the picture. It is the only thing in the
   header link and the only thing naming the brand in the footer, so it
   carries the name itself; alt is one of the attributes the translator
   already walks, so it is in all twelve languages like everything else. */
const NAME = 'ARQR360, AR catalogs for retail';

const FILES = ['index.html', 'catalog.html'];
const esc = (t) => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

(async () => {
  /* the pages' own asset version, so bump-assets.js keeps owning it */
  const version = (fs.readFileSync('index.html', 'utf8')
    .match(/\?v=(\d+)(?![0-9a-zA-Z])/) || [, '1'])[1];

  const tag = async (file, cls, label) => {
    const m = await sharp(file).metadata();
    return '<img class="' + cls + '" src="' + file + '?v=' + version + '" ' +
      'width="' + m.width + '" height="' + m.height + '" ' +
      (label ? 'alt="' + NAME + '"' : 'alt="" aria-hidden="true"') +
      ' decoding="async">';
  };

  const full = await tag('assets/logo-bar.png', 'logo-full', true);
  const mark = await tag('assets/logo-mono.png', 'logo-mark', false);
  const block = (indent) =>
    indent + START + '\n' + indent + full + '\n' + indent + mark + '\n' + indent + END;

  let total = 0;
  for (const file of FILES) {
    let s = fs.readFileSync(file, 'utf8');
    let n = 0;

    /* A rerun: replace what is already between the markers. The markers
       go through RegExp, so they are escaped. They were not once, and
       the "|" in the opening one turned the pattern into an alternation
       that matched each half separately and wrote the logo in twice. */
    s = s.replace(new RegExp('([ \\t]*)' + esc(START) + '[\\s\\S]*?' + esc(END), 'g'),
      (m, indent) => { n++; return block(indent); });

    /* A page with no markers gets them from its logo link, so a new page
       only has to carry an empty <a class="logo"></a> for this to fill. */
    if (!n) {
      s = s.replace(/([ \t]*)<a class="logo"([^>]*)>[\s\S]*?<\/a>/g, (m, indent, attrs) => {
        n++;
        return indent + '<a class="logo"' + attrs + '>\n' +
          block(indent + '  ') + '\n' + indent + '</a>';
      });
    }

    fs.writeFileSync(file, s, 'utf8');
    console.log('  ' + file.padEnd(14) + n + ' lockup' + (n === 1 ? '' : 's'));
    total += n;
  }

  const a = await sharp('assets/logo-bar.png').metadata();
  const b = await sharp('assets/logo-mono.png').metadata();
  console.log('  lockup ' + a.width + '×' + a.height + ' (' + (a.width / a.height).toFixed(3) +
    ':1), monogram ' + b.width + '×' + b.height + ' (' + (b.width / b.height).toFixed(3) +
    ':1), into ' + total + ' places at v=' + version);
  if (!total) throw new Error('nothing was written: no markers and no logo link');
})();
