/* ------------------------------------------------------------------
   Writes the logo into the pages, as markup rather than as a picture.

   Inline svg because everything the raster made hard goes away with it.
   There is no request, so the logo is painted with the first frame
   instead of arriving late. It has a viewBox, so a height is enough and
   the width follows: no more stating both at seven breakpoints and no
   more object-fit guarding against a squash. Its ink is currentColor and
   its accent is var(--accent), so the footer, the bar and anywhere dark
   are the same markup with a different colour on the parent.

   The block between the markers is generated. Run this after changing
   logo-design.js:  npm run logo
   ------------------------------------------------------------------ */
'use strict';
const fs = require('fs');
const L = require('./logo-design');

const START = '<!-- logo:start, generated by logo-write.js -->';
const END = '<!-- logo:end -->';

const esc = (t) => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/* ink follows the parent's colour, the accent is the page's own token */
const art = L.lockup({ ink: 'currentColor', hot: 'var(--accent)' });

/* Named rather than hidden. It is the only thing in the header link and
   the only thing naming the brand in the footer, so it carries the name
   itself; aria-label is one of the attributes the translator already
   walks, so it is in all twelve languages like everything else. */
const NAME = 'ARQR360, AR catalogs for retail';

const block = (indent) => {
  const svg = art.svg
    .replace('<svg ', '<svg role="img" aria-label="' + NAME + '" focusable="false" ')
    /* the width and height attributes would fight the CSS; the viewBox is
       what carries the proportion */
    .replace(/ width="\d+" height="\d+"/, '');
  return indent + START + '\n' + indent + svg + '\n' + indent + END;
};

const FILES = ['index.html', 'catalog.html'];
let total = 0;

for (const file of FILES) {
  let s = fs.readFileSync(file, 'utf8');
  let n = 0;

  /* A rerun: replace what is already between the markers. The markers go
     through RegExp, so they are escaped. They were not, and the "|" in
     the opening one turned the pattern into an alternation that matched
     each half separately and wrote the logo into the page twice. */
  s = s.replace(new RegExp('([ \\t]*)' + esc(START) + '[\\s\\S]*?' + esc(END), 'g'),
    (m, indent) => { n++; return block(indent); });

  /* A page with no markers gets them from its logo link, so a new page
     only has to carry an empty <a class="logo"></a> for this to fill it. */
  if (!n) {
    s = s.replace(/([ \t]*)<a class="logo"([^>]*)>[\s\S]*?<\/a>/g, (m, indent, attrs) => {
      n++;
      return indent + '<a class="logo"' + attrs + '>\n' +
        block(indent + '  ') + '\n' + indent + '</a>';
    });
  }

  fs.writeFileSync(file, s, 'utf8');
  console.log('  ' + file.padEnd(14) + n + ' lockup' + (n === 1 ? '' : 's'));
  total += n;
}

console.log('  ' + art.w + '×' + art.h + ', ratio ' + art.ratio.toFixed(3) +
            ', ' + (Buffer.byteLength(art.svg) / 1024).toFixed(1) + ' KB of markup each');
if (!total) throw new Error('nothing was written: no markers and no picture to replace');
