/* ------------------------------------------------------------------
   Writes the logo into the pages.

   One picture: the lockup, monogram over wordmark. There used to be a
   second, the monogram alone, for a scrolled phone bar. That bar keeps
   the lockup now (it is narrower at the same height), so the monogram
   was hidden on every page and still downloaded on every page. It is
   gone from the markup; assets/logo-mono.png stays on disk only as the
   source brand-images.js draws the schema logo from.

   Both carry their pixel dimensions as attributes, and the CSS then only
   ever sets a height. The attributes give the browser the proportion
   before the file arrives, so the bar does not jump when it does, and
   the width never has to be restated at seven breakpoints.

   The block between the markers is generated. Run this after
   logo-images.js:  npm run logo
   ------------------------------------------------------------------ */
'use strict';
const fs = require('fs');
const sharp = require('sharp');

const START = '<!-- logo:start, generated by logo-write.js -->';
const END = '<!-- logo:end -->';

/* The picture is the monogram over the ARQR 360 wordmark with the tagline
   cropped off, so this is a complete description of it and not a slogan
   attached to one. It used to read "ARQR360, AR catalogs for retail",
   which described the previous artwork and stopped being true when the
   logo changed. A brand name is also the same in every language, so this
   one needs no dictionary entry, which is one fewer thing to keep in
   step with the markup. */
const NAME = 'ARQR360';

const FILES = ['index.html', 'catalogue.html', 'store.html', 'start.html', 'terms.html', 'privacy.html', 'refund.html'];
const esc = (t) => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

(async () => {
  /* the pages' own asset version, so bump-assets.js keeps owning it */
  const version = (fs.readFileSync('index.html', 'utf8')
    .match(/\?v=(\d+)(?![0-9a-zA-Z])/) || [, '1'])[1];

  const tag = async (file, cls, label) => {
    const m = await sharp(file).metadata();
    return '<img class="' + cls + '" src="' + file + '?v=' + version + '" ' +
      'width="' + m.width + '" height="' + m.height + '" ' +
      (label ? 'alt="' + NAME + '"' : 'alt="" aria-hidden="true"') +
      ' decoding="async">';
  };

  const full = await tag('assets/logo-bar.png', 'logo-full', true);
  const block = (indent) =>
    indent + START + '\n' + indent + full + '\n' + indent + END;

  let total = 0;
  for (const file of FILES) {
    let s = fs.readFileSync(file, 'utf8');
    let n = 0;

    /* A rerun: replace what is already between the markers. The markers
       go through RegExp, so they are escaped. They were not once, and
       the "|" in the opening one turned the pattern into an alternation
       that matched each half separately and wrote the logo in twice. */
    s = s.replace(new RegExp('([ \\t]*)' + esc(START) + '[\\s\\S]*?' + esc(END), 'g'),
      (m, indent) => { n++; return block(indent); });

    /* A page with no markers gets them from its logo link, so a new page
       only has to carry an empty <a class="logo"></a> for this to fill. */
    if (!n) {
      s = s.replace(/([ \t]*)<a class="logo"([^>]*)>[\s\S]*?<\/a>/g, (m, indent, attrs) => {
        n++;
        return indent + '<a class="logo"' + attrs + '>\n' +
          block(indent + '  ') + '\n' + indent + '</a>';
      });
    }

    fs.writeFileSync(file, s, 'utf8');
    console.log('  ' + file.padEnd(14) + n + ' lockup' + (n === 1 ? '' : 's'));
    total += n;
  }

  const a = await sharp('assets/logo-bar.png').metadata();
  console.log('  lockup ' + a.width + '×' + a.height + ' (' + (a.width / a.height).toFixed(3) +
    ':1), into ' + total + ' places at v=' + version);
  if (!total) throw new Error('nothing was written: no markers and no logo link');
})();
