/* ------------------------------------------------------------------
   Everything a search engine or an AI assistant reads about this site,
   written from one place.

   The domain is the first line of the config below and appears nowhere
   else. Canonicals, Open Graph, the sitemap, robots.txt and every
   schema block are generated from it, so moving to a real domain is one
   edit here and one run of `npm run seo`.

   The FAQ is the part worth understanding. Google only honours FAQPage
   markup when the same questions and answers are visible on the page —
   marking up questions a visitor cannot see is against their guidelines
   and can cost you the rich result altogether. So the questions live
   here once, and this writes them into both the visible section and the
   JSON-LD. They cannot drift apart.

   Run:  npm run seo
   ------------------------------------------------------------------ */
'use strict';
const fs = require('fs');

/* ---------------------------------------------------------------- config */
const SITE = {
  /* the one line to change when the real domain lands */
  origin: 'https://arqr-two.vercel.app',
  name: 'ARQR',
  tagline: 'Your showroom, in their room',
  blurb: 'ARQR turns your products into an AR catalog. One QR code and your ' +
         'customers see every piece at true size in their own room. No app to download.',
  /* left empty on purpose: linking to social accounts that do not exist
     yet is a broken signal, not a good one. Add them here when they are real. */
  sameAs: []
};

const FAQ = [
  ['What is ARQR?',
   'ARQR turns your product photographs into 3D models your customers can place in their own ' +
   'room at true size, through one QR code or one link. There is no app to download. It opens ' +
   'in the phone’s own camera on both iPhone and Android.'],

  ['How much does an AR catalog cost?',
   'You pay once to have the catalog built, then a monthly fee keeps it live. At founder pricing ' +
   'that is $249 for 10 products and then $29 a month, $549 for 25 and then $59 a month, or $999 ' +
   'for 50 and then $99 a month. Extra products are $20 each. Above 50 products, or for multiple ' +
   'stores and categories, we quote for the range.'],

  ['Do my customers need to install an app?',
   'No. The catalog opens in the browser, and the AR view uses what is already built into the ' +
   'phone: Quick Look on iPhone and Scene Viewer on Android. Your customer scans the code or ' +
   'taps a link and the product appears in the room in front of them.'],

  ['How long does it take to get my catalog?',
   'About seven days from your photographs arriving. Send your best-selling products first. Every product ' +
   'is built to its real measurements, so a three-metre sofa arrives as a three-metre sofa and the ' +
   'customer can see whether it fits.'],

  ['What do you need from me to start?',
   'Photographs of each product and its real dimensions. If you already have 3D files we can use ' +
   'those instead. We do the modelling, the hosting and the QR code, and orders come to you on ' +
   'WhatsApp or through your own site.']
];

/* name, products, one-time setup at founder pricing, then monthly */
const PLANS = [
  ['Starter',  10, 249, 29],
  ['Studio',   25, 549, 59],
  ['Showroom', 50, 999, 99]
];

const PAGES = [
  { file: 'index.html',   path: '/',        image: '/assets/og-home.jpg',
    title: 'ARQR | Your showroom, in their room',
    desc: SITE.blurb, schema: true, faq: true, priority: '1.0' },
  { file: 'catalog.html', path: '/catalog', image: '/assets/og-catalog.jpg',
    title: 'Sample AR catalogs: furniture, footwear, decor and rugs | ARQR',
    desc: 'Four sample catalogs you can open on your phone. Every product at true size in your own room.',
    priority: '0.9' },
  { file: 'store.html',   path: '/store',   image: '/assets/og-catalog.jpg',
    title: 'AR catalog', desc: null, perShop: true, priority: '0.7', noSitemap: true }
];

const SHOPS = ['novara', 'corso', 'maison', 'terra'];

/* ---------------------------------------------------------------- helpers */
const esc = s => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const START = '  <!-- seo:start | generated by seo.js, do not edit by hand -->';
const END   = '  <!-- seo:end -->';

function headBlock(page){
  const url = SITE.origin + page.path;
  const img = SITE.origin + page.image;
  const desc = page.desc || 'An AR catalog. Every product at true size, in your own space.';
  const L = [];

  L.push(START);
  L.push('  <link rel="canonical" href="' + url + '">');
  L.push('');
  L.push('  <meta property="og:type" content="website">');
  L.push('  <meta property="og:site_name" content="' + esc(SITE.name) + '">');
  L.push('  <meta property="og:title" content="' + esc(page.title) + '">');
  L.push('  <meta property="og:description" content="' + esc(desc) + '">');
  L.push('  <meta property="og:url" content="' + url + '">');
  L.push('  <meta property="og:image" content="' + img + '">');
  L.push('  <meta property="og:image:width" content="1200">');
  L.push('  <meta property="og:image:height" content="630">');
  L.push('  <meta property="og:locale" content="en">');
  L.push('');
  L.push('  <meta name="twitter:card" content="summary_large_image">');
  L.push('  <meta name="twitter:title" content="' + esc(page.title) + '">');
  L.push('  <meta name="twitter:description" content="' + esc(desc) + '">');
  L.push('  <meta name="twitter:image" content="' + img + '">');
  L.push('');
  L.push('  <link rel="icon" href="/favicon.svg" type="image/svg+xml">');
  L.push('  <link rel="icon" href="/favicon.ico" sizes="32x32">');
  L.push('  <link rel="apple-touch-icon" href="/apple-touch-icon.png">');
  L.push('  <meta name="theme-color" content="#E0682A">');

  if (page.schema){
    const org = {
      '@context': 'https://schema.org', '@type': 'Organization',
      name: SITE.name, url: SITE.origin + '/',
      logo: SITE.origin + '/assets/logo-mark.png',
      description: SITE.blurb
    };
    if (SITE.sameAs.length) org.sameAs = SITE.sameAs;

    const site = {
      '@context': 'https://schema.org', '@type': 'WebSite',
      name: SITE.name, url: SITE.origin + '/', inLanguage: 'en'
      /* no SearchAction: there is no site search, and claiming one that
         does not exist is the kind of thing that gets markup ignored */
    };

    const service = {
      '@context': 'https://schema.org', '@type': 'Service',
      name: 'AR product catalog', provider: { '@type': 'Organization', name: SITE.name },
      description: SITE.blurb,
      /* two prices, and the markup says which is which. The setup fee is
         the Offer's price because it is what is paid to start; the monthly
         rides alongside it as its own specification rather than being
         averaged into one misleading number. */
      offers: PLANS.map(([name, count, setup, monthly]) => ({
        '@type': 'Offer', name: name,
        description: count + ' AR products, built for you',
        price: String(setup), priceCurrency: 'USD',
        priceSpecification: [
          {
            '@type': 'UnitPriceSpecification',
            name: 'One-time setup', price: String(setup), priceCurrency: 'USD'
          },
          {
            '@type': 'UnitPriceSpecification',
            name: 'Monthly platform fee', price: String(monthly), priceCurrency: 'USD',
            billingDuration: 1, billingIncrement: 1, unitCode: 'MON'
          }
        ]
      }))
    };

    L.push('');
    [org, site, service].forEach(o => {
      L.push('  <script type="application/ld+json">');
      L.push('  ' + JSON.stringify(o, null, 2).split('\n').join('\n  '));
      L.push('  </script>');
    });

    if (page.faq){
      const faq = {
        '@context': 'https://schema.org', '@type': 'FAQPage',
        mainEntity: FAQ.map(([q, a]) => ({
          '@type': 'Question', name: q,
          acceptedAnswer: { '@type': 'Answer', text: a }
        }))
      };
      L.push('  <script type="application/ld+json">');
      L.push('  ' + JSON.stringify(faq, null, 2).split('\n').join('\n  '));
      L.push('  </script>');
    }
  }

  L.push(END);
  return L.join('\n');
}

/* the four shop routes are one file, so their canonical has to be set
   where the shop is known — which is in the page, at run time */
const SHOP_SCRIPT = `<script>
/* /novara, /corso, /maison and /terra are all this one file, so the
   canonical and the share tags cannot be static — they are written here
   once the shop is known. Search engines run this; it is the same
   rendering pass that already sets the title. */
(function (){
  var s = (window.ARQR_STORES || []).filter(function (x){
    var p = location.pathname.replace(/\\/+$/, '').split('/').pop().replace(/\\.html$/, '');
    return x.slug === (new URLSearchParams(location.search).get('s') ||
                       (location.hash || '').replace('#', '') || p);
  })[0];
  if (!s) return;
  var url = '${SITE.origin}/' + s.slug;
  var set = function (sel, attr, val){
    var el = document.head.querySelector(sel);
    if (el) el.setAttribute(attr, val);
  };
  set('link[rel="canonical"]', 'href', url);
  set('meta[property="og:url"]', 'content', url);
  set('meta[property="og:title"]', 'content', s.name + ' | AR catalog');
  set('meta[name="twitter:title"]', 'content', s.name + ' | AR catalog');
})();
</script>`;

/* ---------------------------------------------------------------- write */
let changed = 0;

PAGES.forEach(page => {
  let s = fs.readFileSync(page.file, 'utf8');
  const block = headBlock(page);

  if (s.indexOf(START) > -1){
    s = s.slice(0, s.indexOf(START)) + block + s.slice(s.indexOf(END) + END.length);
  } else {
    const at = s.indexOf('</head>');
    if (at < 0) throw new Error('no </head> in ' + page.file);
    s = s.slice(0, at) + block + '\n' + s.slice(at);
  }

  if (page.perShop && s.indexOf('/novara, /corso, /maison and /terra are all this one file') < 0){
    const at = s.lastIndexOf('</body>');
    s = s.slice(0, at) + SHOP_SCRIPT + '\n' + s.slice(at);
  }

  fs.writeFileSync(page.file, s, 'utf8');
  changed++;
  console.log('  ' + page.file.padEnd(14) + 'canonical ' + SITE.origin + page.path);
});

/* ---- the visible FAQ, from the same source as the markup ---- */
{
  let s = fs.readFileSync('index.html', 'utf8');
  const a = '<!-- faq:start -->', b = '<!-- faq:end -->';
  if (s.indexOf(a) > -1){
    const html = FAQ.map(([q, ans]) =>
      '        <details class="qa rev">\n' +
      '          <summary><span>' + esc(q) + '</span>' +
      '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 9.5 12 15.5 18 9.5" ' +
      'stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg>' +
      '</summary>\n' +
      '          <p>' + esc(ans) + '</p>\n' +
      '        </details>').join('\n');
    s = s.slice(0, s.indexOf(a) + a.length) + '\n' + html + '\n      ' + s.slice(s.indexOf(b));
    fs.writeFileSync('index.html', s, 'utf8');
    console.log('  index.html    ' + FAQ.length + ' questions written to the page and to the FAQ schema');
  } else {
    console.log('  ! no faq:start marker in index.html, schema written, section not');
  }
}

/* ---- robots.txt ---- */
fs.writeFileSync('robots.txt',
  'User-agent: *\n' +
  'Allow: /\n' +
  '\n' +
  '# the models are large and there is nothing to index inside them\n' +
  'Disallow: /assets/shops/\n' +
  '\n' +
  'Sitemap: ' + SITE.origin + '/sitemap.xml\n', 'utf8');

/* ---- sitemap.xml ---- */
const today = new Date().toISOString().slice(0, 10);
const urls = PAGES.filter(p => !p.noSitemap).map(p => ({ loc: SITE.origin + p.path, pri: p.priority }))
  .concat(SHOPS.map(s => ({ loc: SITE.origin + '/' + s, pri: '0.7' })));
fs.writeFileSync('sitemap.xml',
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  urls.map(u =>
    '  <url>\n' +
    '    <loc>' + u.loc + '</loc>\n' +
    '    <lastmod>' + today + '</lastmod>\n' +
    '    <priority>' + u.pri + '</priority>\n' +
    '  </url>').join('\n') + '\n' +
  '</urlset>\n', 'utf8');

console.log('  robots.txt    written');
console.log('  sitemap.xml   ' + urls.length + ' urls');
console.log('');
console.log('  domain lives on line 24 of this file and nowhere else');
