/* Order:  zh  ja  ru  uz  tr  es  fr  de  it  pt  ur   (11) */
module.exports = { t: {

/* ---------------- the bar ---------------- */
'How it works': ['工作方式','使い方','Как это работает','Qanday ishlaydi','Nasıl çalışır','Cómo funciona','Comment ça marche','So funktioniert es','Come funziona','Como funciona','یہ کیسے کام کرتا ہے'],
'Why it works': ['为什么有效','効果がある理由','Почему это работает','Nega samarali','Neden işe yarar','Por qué funciona','Pourquoi ça marche','Warum es funktioniert','Perché funziona','Porque funciona','یہ کیوں کارگر ہے'],
'Pricing': ['价格','料金','Цены','Narxlar','Fiyatlar','Precios','Tarifs','Preise','Prezzi','Preços','قیمتیں'],
'Contact': ['联系我们','お問い合わせ','Контакты','Aloqa','İletişim','Contacto','Contact','Kontakt','Contatti','Contacto','رابطہ'],
'Get your catalog': ['获取你的目录','カタログを作る','Получить каталог','Katalogingizni oling','Kataloğunuzu alın','Consigue tu catálogo','Obtenez votre catalogue','Ihren Katalog holen','Ottieni il tuo catalogo','Obtenha o seu catálogo','اپنا کیٹلاگ حاصل کریں'],
'Back to ARQR': ['返回 ARQR','ARQR に戻る','Назад к ARQR','ARQR ga qaytish','ARQR\'ye dön','Volver a ARQR','Retour à ARQR','Zurück zu ARQR','Torna ad ARQR','Voltar ao ARQR','ARQR پر واپس'],

/* ---------------- opening screen ---------------- */
"80% of sales are lost <em>because customers</em> can't see it in their space.":
  ['80% 的成交流失，<em>只因顾客</em>看不到它在自己家里的样子。',
   '売上の80%が失われるのは、<em>お客様が</em>自分の部屋に置いた姿を見られないからです。',
   '80% продаж теряется, <em>потому что клиент</em> не видит товар у себя дома.',
   'Savdoning 80% yo‘qoladi, <em>chunki xaridor</em> uni o‘z xonasida ko‘ra olmaydi.',
   'Satışların %80\'i kayboluyor, <em>çünkü müşteri</em> ürünü kendi evinde göremiyor.',
   'El 80% de las ventas se pierde <em>porque el cliente</em> no puede verlo en su espacio.',
   '80% des ventes sont perdues <em>parce que le client</em> ne peut pas le voir chez lui.',
   '80% der Verkäufe gehen verloren, <em>weil Kunden</em> es nicht in ihrem Raum sehen.',
   'L\'80% delle vendite si perde <em>perché il cliente</em> non lo vede in casa sua.',
   '80% das vendas perdem-se <em>porque o cliente</em> não o vê no seu espaço.',
   '‏80٪ فروخت ضائع ہو جاتی ہے <em>کیونکہ گاہک</em> اسے اپنی جگہ میں نہیں دیکھ پاتا۔'],
'ARQR lets your customers place products in their own space — in real size, real time.':
  ['ARQR 让顾客把产品放进自己的空间——真实尺寸，实时呈现。',
   'ARQR なら、お客様が実寸の商品をその場で自分の部屋に置けます。',
   'ARQR позволяет клиентам поставить товар у себя дома — в реальном размере и в реальном времени.',
   'ARQR xaridorlarga mahsulotni o‘z xonasiga qo‘yish imkonini beradi — haqiqiy o‘lchamda, real vaqtda.',
   'ARQR, müşterilerinizin ürünü kendi mekânına yerleştirmesini sağlar — gerçek boyutta, anında.',
   'ARQR permite a tus clientes colocar los productos en su propio espacio, a tamaño real y al instante.',
   'ARQR permet à vos clients de placer vos produits chez eux, à taille réelle et en direct.',
   'Mit ARQR stellen Ihre Kunden Produkte in ihren eigenen Raum — in echter Größe, in Echtzeit.',
   'ARQR permette ai tuoi clienti di posare i prodotti in casa loro, a grandezza reale e in tempo reale.',
   'O ARQR permite aos seus clientes colocar os produtos no seu espaço — em tamanho real, na hora.',
   'ARQR آپ کے گاہکوں کو مصنوعات اپنی جگہ میں رکھنے دیتا ہے — اصل سائز میں، اسی وقت۔'],
'See it. Love it. Buy it.': ['看见它。爱上它。买下它。','見る。惚れる。買う。','Увидел. Понравилось. Купил.','Ko‘ring. Yoqtiring. Xarid qiling.','Gör. Beğen. Satın al.','Míralo. Enamórate. Cómpralo.','Voyez-le. Aimez-le. Achetez-le.','Sehen. Lieben. Kaufen.','Guardalo. Amalo. Compralo.','Veja. Adore. Compre.','دیکھیں۔ پسند کریں۔ خریدیں۔'],
'From uncertainty to confidence in one scan.': ['一次扫码，从犹豫到确定。','スキャン一回で、迷いが確信に変わります。','Одно сканирование — и сомнения сменяются уверенностью.','Bitta skan — shubha o‘rniga ishonch.','Tek bir taramada tereddütten güvene.','De la duda a la confianza con un solo escaneo.','Du doute à la confiance en un seul scan.','Ein Scan — aus Unsicherheit wird Gewissheit.','Da dubbio a certezza con una sola scansione.','Da dúvida à confiança com um único scan.','ایک اسکین میں شک سے یقین تک۔'],
'Apply for your AR catalog': ['申请你的 AR 目录','AR カタログを申し込む','Заказать AR-каталог','AR katalogingizga ariza bering','AR kataloğunuz için başvurun','Solicita tu catálogo AR','Demandez votre catalogue AR','AR-Katalog anfragen','Richiedi il tuo catalogo AR','Peça o seu catálogo AR','اپنے AR کیٹلاگ کے لیے درخواست دیں'],
'See a live example': ['查看真实示例','実際の例を見る','Посмотреть живой пример','Jonli namunani ko‘ring','Canlı bir örnek görün','Ver un ejemplo real','Voir un exemple réel','Echtes Beispiel ansehen','Guarda un esempio reale','Ver um exemplo real','ایک حقیقی مثال دیکھیں'],
'No app to download': ['无需下载应用','アプリ不要','Без приложений','Ilova kerak emas','Uygulama gerekmez','Sin descargar nada','Aucune application','Keine App nötig','Nessuna app da scaricare','Sem instalar nada','کوئی ایپ ڈاؤن لوڈ نہیں'],
'iPhone &amp; Android': ['iPhone 和 Android','iPhone と Android','iPhone и Android','iPhone va Android','iPhone ve Android','iPhone y Android','iPhone et Android','iPhone &amp; Android','iPhone e Android','iPhone e Android','آئی فون اور اینڈرائیڈ'],
'Live in 7 days': ['7 天上线','7日で公開','Готово за 7 дней','7 kunda tayyor','7 günde hazır','Listo en 7 días','Prêt en 7 jours','In 7 Tagen live','Pronto in 7 giorni','Pronto em 7 dias','‏7 دن میں تیار'],
'See a real catalog first': ['先看一个真实目录','まず本物のカタログを','Сначала посмотрите настоящий каталог','Avval haqiqiy katalogni ko‘ring','Önce gerçek bir katalog görün','Mira primero un catálogo real','Voyez d\'abord un vrai catalogue','Erst einen echten Katalog ansehen','Guarda prima un catalogo vero','Veja primeiro um catálogo real','پہلے ایک اصلی کیٹلاگ دیکھیں'],
"Point your phone camera at this code. Four real catalogs — furniture, footwear, decor, carpets — each one a single shop's own.":
  ['用手机相机对准这个二维码。四个真实目录——家具、鞋履、家饰、地毯——每个都属于一家店。',
   'スマホのカメラをこのコードに向けてください。家具・靴・インテリア・カーペットの4つのカタログは、それぞれ一つの店のものです。',
   'Наведите камеру телефона на этот код. Четыре настоящих каталога — мебель, обувь, декор, ковры — каждый принадлежит одному магазину.',
   'Telefon kamerasini shu kodga qarating. To‘rtta haqiqiy katalog — mebel, poyabzal, dekor, gilam — har biri bitta do‘konniki.',
   'Telefon kameranızı bu koda tutun. Dört gerçek katalog — mobilya, ayakkabı, dekor, halı — her biri tek bir mağazanın.',
   'Apunta la cámara del móvil a este código. Cuatro catálogos reales — muebles, calzado, decoración, alfombras — cada uno de una sola tienda.',
   'Pointez l\'appareil photo de votre téléphone sur ce code. Quatre vrais catalogues — mobilier, chaussures, décoration, tapis — chacun appartenant à une seule boutique.',
   'Richten Sie die Handykamera auf diesen Code. Vier echte Kataloge — Möbel, Schuhe, Deko, Teppiche — jeder gehört einem einzigen Laden.',
   'Punta la fotocamera del telefono su questo codice. Quattro cataloghi veri — mobili, scarpe, decoro, tappeti — ognuno di un solo negozio.',
   'Aponte a câmara do telemóvel para este código. Quatro catálogos reais — mobiliário, calçado, decoração, tapetes — cada um de uma só loja.',
   'اپنے فون کا کیمرہ اس کوڈ پر رکھیں۔ چار اصلی کیٹلاگ — فرنیچر، جوتے، ڈیکور، قالین — ہر ایک کسی ایک دکان کا اپنا۔'],
"Tap this code. Four real catalogs — furniture, footwear, decor, carpets — each one a single shop's own.":
  ['点击这个二维码。四个真实目录——家具、鞋履、家饰、地毯——每个都属于一家店。',
   'このコードをタップしてください。家具・靴・インテリア・カーペットの4つのカタログは、それぞれ一つの店のものです。',
   'Нажмите на этот код. Четыре настоящих каталога — мебель, обувь, декор, ковры — каждый принадлежит одному магазину.',
   'Shu kodni bosing. To‘rtta haqiqiy katalog — mebel, poyabzal, dekor, gilam — har biri bitta do‘konniki.',
   'Bu koda dokunun. Dört gerçek katalog — mobilya, ayakkabı, dekor, halı — her biri tek bir mağazanın.',
   'Toca este código. Cuatro catálogos reales — muebles, calzado, decoración, alfombras — cada uno de una sola tienda.',
   'Touchez ce code. Quatre vrais catalogues — mobilier, chaussures, décoration, tapis — chacun appartenant à une seule boutique.',
   'Tippen Sie auf diesen Code. Vier echte Kataloge — Möbel, Schuhe, Deko, Teppiche — jeder gehört einem einzigen Laden.',
   'Tocca questo codice. Quattro cataloghi veri — mobili, scarpe, decoro, tappeti — ognuno di un solo negozio.',
   'Toque neste código. Quatro catálogos reais — mobiliário, calçado, decoração, tapetes — cada um de uma só loja.',
   'اس کوڈ کو دبائیں۔ چار اصلی کیٹلاگ — فرنیچر، جوتے، ڈیکور، قالین — ہر ایک کسی ایک دکان کا اپنا۔'],
'See the samples': ['查看示例','サンプルを見る','Смотреть примеры','Namunalarni ko‘ring','Örnekleri görün','Ver los ejemplos','Voir les exemples','Beispiele ansehen','Guarda gli esempi','Ver os exemplos','نمونے دیکھیں'],
'AR preview': ['AR 预览','AR プレビュー','AR-просмотр','AR ko‘rinish','AR önizleme','Vista AR','Aperçu AR','AR-Vorschau','Anteprima AR','Pré-visualização AR','AR پیش منظر'],
'True to scale': ['真实比例','実寸どおり','Реальный масштаб','Haqiqiy o‘lcham','Gerçek ölçekte','A escala real','À taille réelle','Maßstabsgetreu','In scala reale','À escala real','اصل پیمانے پر'],
'1. Scan': ['1. 扫码','1. スキャン','1. Скан','1. Skanlash','1. Tara','1. Escanea','1. Scannez','1. Scannen','1. Scansiona','1. Digitalize','‏1۔ اسکین'],
'Scan any product': ['扫描任意产品','商品をスキャン','Отсканируйте товар','Istalgan mahsulotni skanlang','Herhangi bir ürünü tarayın','Escanea cualquier producto','Scannez un produit','Produkt scannen','Scansiona un prodotto','Digitalize qualquer produto','کسی بھی پروڈکٹ کو اسکین کریں'],
'2. Place': ['2. 放置','2. 配置','2. Разместите','2. Joylashtiring','2. Yerleştir','2. Colócalo','2. Placez','2. Platzieren','2. Posiziona','2. Coloque','‏2۔ رکھیں'],
'Place in your space': ['放进你的空间','部屋に置く','Поставьте у себя дома','O‘z xonangizga qo‘ying','Kendi mekânınıza koyun','Colócalo en tu espacio','Placez-le chez vous','In Ihren Raum stellen','Mettilo in casa tua','Coloque no seu espaço','اپنی جگہ میں رکھیں'],
'3. View': ['3. 查看','3. 見る','3. Смотрите','3. Ko‘ring','3. Gör','3. Míralo','3. Regardez','3. Ansehen','3. Guarda','3. Veja','‏3۔ دیکھیں'],
'See in real size &amp; light': ['真实尺寸与光线','実寸と実際の光で','В реальном размере и свете','Haqiqiy o‘lcham va yorug‘likda','Gerçek boyut ve ışıkta','A tamaño y luz reales','Taille et lumière réelles','In echter Größe und Licht','A dimensione e luce reali','Em tamanho e luz reais','اصل سائز اور روشنی میں'],
'4. Order': ['4. 下单','4. 注文','4. Заказ','4. Buyurtma','4. Sipariş ver','4. Compra','4. Commandez','4. Bestellen','4. Ordina','4. Encomende','‏4۔ آرڈر'],
'Buy with confidence': ['放心购买','安心して購入','Покупайте уверенно','Ishonch bilan xarid qiling','Güvenle satın alın','Compra con confianza','Achetez en confiance','Sicher kaufen','Compra con fiducia','Compre com confiança','اعتماد کے ساتھ خریدیں'],

/* ---------------- why it works ---------------- */
'A photo asks them to imagine it. <em>AR just shows them.</em>':
  ['照片让人去想象。<em>AR 直接让人看见。</em>',
   '写真は想像を求めます。<em>AR は見せるだけです。</em>',
   'Фото просит представить. <em>AR просто показывает.</em>',
   'Surat tasavvur qilishni so‘raydi. <em>AR shunchaki ko‘rsatadi.</em>',
   'Fotoğraf hayal etmenizi ister. <em>AR ise gösterir.</em>',
   'Una foto pide imaginarlo. <em>La AR simplemente lo enseña.</em>',
   'Une photo demande d\'imaginer. <em>La RA, elle, montre.</em>',
   'Ein Foto verlangt Vorstellungskraft. <em>AR zeigt es einfach.</em>',
   'Una foto chiede di immaginare. <em>L\'AR lo mostra e basta.</em>',
   'Uma foto pede que imagine. <em>A RA simplesmente mostra.</em>',
   'تصویر تصور کرنے کو کہتی ہے۔ <em>AR سیدھا دکھا دیتا ہے۔</em>'],
'When customers can see your product in their own space, they understand it better and buy with confidence.':
  ['当顾客能在自己的空间里看到产品，他们理解得更清楚，也买得更放心。',
   'お客様が自分の部屋で商品を見られると、理解が深まり、安心して購入できます。',
   'Когда клиент видит товар у себя дома, он понимает его лучше и покупает увереннее.',
   'Xaridor mahsulotni o‘z xonasida ko‘rsa, uni yaxshiroq tushunadi va ishonch bilan sotib oladi.',
   'Müşteri ürünü kendi mekânında görebildiğinde daha iyi anlar ve güvenle satın alır.',
   'Cuando el cliente ve tu producto en su propio espacio, lo entiende mejor y compra con confianza.',
   'Quand le client voit votre produit chez lui, il le comprend mieux et achète en confiance.',
   'Wenn Kunden Ihr Produkt im eigenen Raum sehen, verstehen sie es besser und kaufen sicherer.',
   'Quando il cliente vede il prodotto in casa sua, lo capisce meglio e compra con fiducia.',
   'Quando o cliente vê o seu produto no espaço dele, percebe-o melhor e compra com confiança.',
   'جب گاہک آپ کی چیز اپنی جگہ میں دیکھ لے تو وہ اسے بہتر سمجھتا ہے اور اعتماد سے خریدتا ہے۔'],
'Move to compare': ['滑动对比','スライドで比較','Двигайте для сравнения','Solishtirish uchun suring','Karşılaştırmak için kaydırın','Desliza para comparar','Faites glisser pour comparer','Zum Vergleichen schieben','Trascina per confrontare','Deslize para comparar','موازنے کے لیے حرکت دیں'],
'The problem': ['问题','課題','Проблема','Muammo','Sorun','El problema','Le problème','Das Problem','Il problema','O problema','مسئلہ'],
"The hardest part of buying online isn't finding the product. <em>It's knowing whether it belongs in their space.</em>":
  ['网购最难的不是找到商品，<em>而是判断它是否适合自己的空间。</em>',
   'ネット購入で一番難しいのは商品探しではなく、<em>それが自分の部屋に合うかどうかです。</em>',
   'Самое трудное в онлайн-покупке — не найти товар, <em>а понять, впишется ли он в дом.</em>',
   'Onlayn xaridda eng qiyini mahsulotni topish emas, <em>uning xonaga mos kelishini bilishdir.</em>',
   'İnternetten alışverişin en zor kısmı ürünü bulmak değil, <em>onun o mekâna uyup uymayacağını bilmektir.</em>',
   'Lo difícil de comprar en línea no es encontrar el producto, <em>sino saber si encaja en su espacio.</em>',
   'Le plus dur en ligne n\'est pas de trouver le produit, <em>mais de savoir s\'il a sa place chez soi.</em>',
   'Das Schwerste beim Online-Kauf ist nicht, das Produkt zu finden, <em>sondern zu wissen, ob es in den Raum passt.</em>',
   'La parte difficile dell\'acquisto online non è trovare il prodotto, <em>ma capire se sta bene in casa.</em>',
   'O mais difícil de comprar online não é encontrar o produto, <em>é saber se ele cabe no espaço.</em>',
   'آن لائن خریداری کا مشکل ترین حصہ چیز ڈھونڈنا نہیں، <em>بلکہ یہ جاننا ہے کہ وہ اُن کی جگہ میں جچے گی یا نہیں۔</em>'],
'The solution': ['解决办法','解決策','Решение','Yechim','Çözüm','La solución','La solution','Die Lösung','La soluzione','A solução','حل'],
'AR removes <em>the guesswork.</em>':
  ['AR 消除了<em>猜测。</em>','AR が<em>推測をなくします。</em>','AR убирает <em>догадки.</em>','AR <em>taxminni</em> yo‘q qiladi.','AR <em>tahmini</em> ortadan kaldırır.','La AR elimina <em>las conjeturas.</em>','La RA supprime <em>les suppositions.</em>','AR beendet <em>das Rätselraten.</em>','L\'AR elimina <em>i dubbi.</em>','A RA elimina <em>as suposições.</em>','AR <em>اندازوں کو</em> ختم کر دیتا ہے۔'],
'Instead of asking customers to imagine your product in their space, let them see it there.':
  ['与其让顾客想象产品在自己家里的样子，不如让他们直接看见。',
   'お客様に想像させるのではなく、実際にその場で見せましょう。',
   'Вместо того чтобы просить клиента представить товар у себя дома, покажите его там.',
   'Xaridordan tasavvur qilishni so‘rash o‘rniga, unga o‘sha yerda ko‘rsating.',
   'Müşteriden hayal etmesini istemek yerine, ona orada gösterin.',
   'En lugar de pedirle al cliente que lo imagine en su espacio, deja que lo vea allí.',
   'Plutôt que de demander au client d\'imaginer, montrez-lui directement chez lui.',
   'Statt Kunden bitten, es sich vorzustellen — zeigen Sie es ihnen dort.',
   'Invece di chiedere al cliente di immaginarlo, faglielo vedere lì.',
   'Em vez de pedir ao cliente que imagine, deixe-o ver ali mesmo.',
   'گاہک سے تصور کرنے کو کہنے کے بجائے، اسے وہیں دکھا دیں۔'],
'Will it fit?': ['放得下吗？','入るかな？','Поместится ли?','Sig‘adimi?','Sığar mı?','¿Cabrá?','Est-ce que ça rentre ?','Passt es?','Ci starà?','Vai caber?','کیا یہ سما جائے گا؟'],
'Will it look right?': ['好看吗？','似合うかな？','Будет ли смотреться?','Yarashadimi?','Yakışır mı?','¿Quedará bien?','Est-ce que ça ira ?','Passt es optisch?','Starà bene?','Vai ficar bem?','کیا یہ جچے گا؟'],
'Will I regret buying it?': ['会后悔吗？','後悔しないかな？','Не пожалею ли я?','Afsuslanamanmi?','Pişman olur muyum?','¿Me arrepentiré?','Vais-je le regretter ?','Werde ich es bereuen?','Me ne pentirò?','Vou arrepender-me?','کیا مجھے پچھتاوا ہوگا؟']

}};
